v1.17.2:
  etcd: zdnscloud/coreos-etcd:v3.4.3
  kubernetes: zdnscloud/hyperkube:v1.17.2
  alpine: zdnscloud/zke-tools:v0.1.40
  nginx_proxy: zdnscloud/zke-tools:v0.1.40
  cert_downloader: zdnscloud/zke-tools:v0.1.40
  kubernetes_services_sidecar: zdnscloud/zke-tools:v0.1.40
  flannel: zdnscloud/coreos-flannel:v0.11.0
  flannel_cni: zdnscloud/coreos-flannel-cni:v0.3.0
  flannel_sidecar: zdnscloud/flannel-directrouting:v0.0.1
  calico_node: zdnscloud/calico-node:v3.10.2
  calico_cni: zdnscloud/calico-cni:v3.10.2
  calico_ctl: zdnscloud/calico-ctl:v3.10.2
  pod_infra_container: zdnscloud/pause-amd64:3.1
  ingress: zdnscloud/nginx-ingress-controller:0.28.0
  ingress_backend: zdnscloud/nginx-ingress-controller-defaultbackend:1.4
  coredns: zdnscloud/coredns:1.6.5
  coredns_autoscaler: zdnscloud/cluster-proportional-autoscaler-amd64:1.7.1
  cluster_agent: zdnscloud/cluster-agent:latest
  node_agent: zdnscloud/node-agent:v1.3.1
  metrics_server: zdnscloud/metrics-server-amd64:v0.3.6
  zke_remover: zdnscloud/zke-remove:v0.7
  storage_operator: zdnscloud/storage-operator:v3.5.7
  zcloud_shell: zdnscloud/kubectl:v1.17.2
  zcloud_proxy: zdnscloud/zcloud-proxy:v1.0.1
  zcloud_lbcontroller: zdnscloud/elb-controller:v0.0.5
  application_operator: zdnscloud/application-operator:latest
  service_mesh:
    controller: zdnscloud/linkerd-io-controller:stable-2.6.0
    proxy: zdnscloud/linkerd-io-proxy:stable-2.6.0
    proxy_init: zdnscloud/linkerd-io-proxy-init:v1.2.0
    web: zdnscloud/linkerd-io-web:stable-2.6.0
    prometheus: prom/prometheus:v2.11.1
    grafana: zdnscloud/linkerd-io-grafana:stable-2.6.0
  cicd:
    controller: docker.io/zdnscloud/tekton-pipeline-controller:v0.10.1
    kube_config_writer: docker.io/zdnscloud/tekton-pipeline-kubeconfigwriter:v0.10.1
    creds_initer: docker.io/zdnscloud/tekton-pipeline-creds-init:v0.10.1
    git_initer: docker.io/zdnscloud/tekton-pipeline-git-init:v0.10.1
    entrypointer: docker.io/zdnscloud/tekton-pipeline-entrypoint:v0.10.1
    image_digest_exporter: docker.io/zdnscloud/tekton-pipeline-imagedigestexporter:v0.10.1
    pull_request_initer: docker.io/zdnscloud/tekton-pipeline-pullrequest-init:v0.10.1
    gcs_fetcher: docker.io/zdnscloud/tekton-pipeline-gcs-fetcher:v0.10.1
    webhook: docker.io/zdnscloud/tekton-pipeline-webhook:v0.10.1
    dashboard: docker.io/zdnscloud/tekton-dashboard-dashboard:v0.5.1
